---
source:
  bucket: s3://uploads
  posix_path: /corral/s3/ingest/uploads
destination:
  bucket: agave://data-sd2e-community/uploads
  posix_path: /work/projects/SD2E-Community/prod/data/uploads
  grants:
    - username: world
      pem: READ
      recursive: False
routings:
  capture-fixity:
    - "."
  etl-pipeline-support:
    - ".json$"
linked_reactors:
  capture-fixity:
    id: EqvOPJoZB5wEV
    ignore_err: false
  etl-pipeline-support:
    id: 6rgbzrjRKoBDk
    ignore_err: false
logs:
  level: DEBUG
  token: ~
slack:
  webhook: ~
batch:
  size: 1000
  task_sleep_duration: 0.1
  sleep_duration: 10
  randomize_sleep: true
