---
source:
  bucket: s3://uploads
  posix_path: /corral/s3/ingest/uploads
destination:
  bucket: agave://data-sd2e-community/uploads
  posix_path: /work/projects/SD2E-Community/prod/data/uploads
  grants:
    - username: world
      pem: READ
      recursive: False
routings:
  capture-fixity:
    - "."
  etl-pipeline-support:
    - ".json$"
linked_reactors:
  capture-fixity:
    id: EqvOPJoZB5wEV
    ignore_err: false
  etl-pipeline-support:
    id: kORGmrmKxaOY3
    ignore_err: false
logs:
  level: INFO
  token: ~
slack:
  webhook: ~
